language: go

go:
  - 1.9
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

sudo: required

services:
  - docker

install:
  - make install

script:
  - make test-integration

after_success:
  - bash <(curl -s https://codecov.io/bash)
